"""仓储接口声明（领域层）。

领域层只依赖这些抽象，具体实现位于 infrastructure/repositories。
使用 Protocol 实现结构化子类型，避免领域层依赖任何持久化框架。
"""

from datetime import date, datetime
from typing import Optional, Protocol, Sequence

from app.domain.entities.catalog import BookTitle, LibraryItem
from app.domain.entities.circulation import FineRecord, Loan, LostItem, Reservation
from app.domain.entities.identity import Account, BorrowCard, Librarian, Reader
from app.domain.entities.review import BookReview
from app.domain.policies.borrow_policy import BorrowPolicy
from app.domain.policies.compensation_policy import CompensationPolicy
from app.domain.policies.fine_rule import FineRule
from app.domain.value_objects.enums import ItemType, LoanStatus, ReaderType, ReviewStatus


class AccountRepository(Protocol):
    def find_by_username(self, username: str) -> Optional[Account]: ...
    def find_by_id(self, account_id: int) -> Optional[Account]: ...
    def add(self, account: Account) -> Account: ...


class TokenRepository(Protocol):
    def save(self, token: str, account_id: int, expires_at: datetime) -> None: ...
    def find_account_id(self, token: str) -> Optional[int]: ...
    def delete(self, token: str) -> None: ...


class ReaderRepository(Protocol):
    def get(self, reader_id: int) -> Optional[Reader]: ...
    def find_by_account_id(self, account_id: int) -> Optional[Reader]: ...
    def add(self, reader: Reader) -> Reader: ...
    def save(self, reader: Reader) -> Reader: ...
    def search(
        self, name: Optional[str], reader_type: Optional[ReaderType], page: int, page_size: int
    ) -> tuple[Sequence[Reader], int]: ...


class LibrarianRepository(Protocol):
    def get(self, librarian_id: int) -> Optional[Librarian]: ...
    def list(self, page: int, page_size: int) -> tuple[Sequence[Librarian], int]: ...
    def add(self, librarian: Librarian) -> Librarian: ...
    def save(self, librarian: Librarian) -> Librarian: ...
    def delete(self, librarian_id: int) -> None: ...


class BorrowCardRepository(Protocol):
    def find_by_no(self, card_no: str) -> Optional[BorrowCard]: ...
    def find_active_by_reader(self, reader_id: int) -> Optional[BorrowCard]: ...
    def get(self, card_id: int) -> Optional[BorrowCard]: ...
    def add(self, card: BorrowCard) -> BorrowCard: ...
    def save(self, card: BorrowCard) -> BorrowCard: ...


class TitleRepository(Protocol):
    def get(self, title_id: int) -> Optional[BookTitle]: ...
    def find_by_isbn(self, isbn: str) -> Optional[BookTitle]: ...
    def search(
        self,
        keyword: Optional[str],
        author: Optional[str],
        category: Optional[str],
        item_type: Optional[ItemType],
        page: int,
        page_size: int,
    ) -> tuple[Sequence[BookTitle], int]: ...
    def add(self, title: BookTitle) -> BookTitle: ...
    def save(self, title: BookTitle) -> BookTitle: ...


class ItemRepository(Protocol):
    def get(self, item_id: int) -> Optional[LibraryItem]: ...
    def find_by_barcode(self, barcode: str) -> Optional[LibraryItem]: ...
    def find_available_by_title(self, title_id: int) -> Optional[LibraryItem]: ...
    def save(self, item: LibraryItem) -> LibraryItem: ...
    def add(self, item: LibraryItem) -> LibraryItem: ...
    def list_by_title(self, title_id: int) -> Sequence[LibraryItem]: ...
    def count_available(self, title_id: int) -> int: ...


class LoanRepository(Protocol):
    def get(self, loan_id: int) -> Optional[Loan]: ...
    def add(self, loan: Loan) -> Loan: ...
    def save(self, loan: Loan) -> Loan: ...
    def find_active_by_item(self, item_id: int) -> Optional[Loan]: ...
    def count_active(self, reader_id: int, item_type: Optional[ItemType] = None) -> int: ...
    def count_overdue(self, reader_id: int, today: date) -> int: ...
    def has_active_loan_of_title(self, reader_id: int, title_id: int) -> bool: ...
    def list_return_requests(self) -> list[dict]: ...
    def list_by_reader(
        self, reader_id: int, status: Optional[LoanStatus] = None
    ) -> Sequence[Loan]: ...


class FineRepository(Protocol):
    def add(self, fine: FineRecord) -> FineRecord: ...
    def get(self, fine_id: int) -> Optional[FineRecord]: ...
    def save(self, fine: FineRecord) -> FineRecord: ...
    def has_unpaid(self, reader_id: int) -> bool: ...


class LostRepository(Protocol):
    def add(self, lost: LostItem) -> LostItem: ...
    def get(self, lost_id: int) -> Optional[LostItem]: ...
    def save(self, lost: LostItem) -> LostItem: ...
    def has_unpaid(self, reader_id: int) -> bool: ...


class ReservationRepository(Protocol):
    def get(self, reservation_id: int) -> Optional[Reservation]: ...
    def add(self, reservation: Reservation) -> Reservation: ...
    def save(self, reservation: Reservation) -> Reservation: ...
    def has_effective(self, reader_id: int, title_id: int, today: date) -> bool: ...
    def count_effective_before(self, title_id: int, created_at: datetime, today: date) -> int: ...
    def count_effective_by_others(
        self, title_id: int, reader_id: int, today: date
    ) -> int: ...
    def expire_outdated(self, reader_id: int, title_id: int, today: date) -> int: ...


class ReviewRepository(Protocol):
    def get(self, review_id: int) -> Optional[BookReview]: ...
    def find_by_reader_and_title(
        self, reader_id: int, title_id: int
    ) -> Optional[BookReview]: ...
    def list_by_status(
        self, title_id: int, status: ReviewStatus
    ) -> Sequence[BookReview]: ...
    def save(self, review: BookReview) -> BookReview: ...


class PolicyRepository(Protocol):
    def borrow_policies(self) -> Sequence[BorrowPolicy]: ...
    def upsert_borrow_policy(self, policy: BorrowPolicy) -> BorrowPolicy: ...
    def get_fine_rule(self, item_category: str) -> Optional[FineRule]: ...
    def upsert_fine_rule(self, rule: FineRule) -> FineRule: ...
    def get_compensation_policy(self, item_type: ItemType) -> Optional[CompensationPolicy]: ...
